plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/heejunann/sunswim-blog/site/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/heejunann/sunswim-blog/site"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]